version: "3"
services:
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-volume:/redis-data
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379
volumes:
  db-volume:
  redis-volume:
